"""metadata_repository

Revision ID: 0001
Revises:
Create Date: 2026-08-02 00:13:07.854770
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("connection_ref", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("baseline_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("key", name=op.f("uq_data_sources_key")),
    )
    op.create_table(
        "pipelines",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("airflow_dag_id", sa.String(length=250), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=False),
        sa.Column(
            "criticality",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="pipeline_criticality",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipelines")),
        sa.UniqueConstraint("airflow_dag_id", name=op.f("uq_pipelines_airflow_dag_id")),
        sa.UniqueConstraint("key", name=op.f("uq_pipelines_key")),
    )
    op.create_table(
        "datasets",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(length=63), nullable=False),
        sa.Column("table_name", sa.String(length=63), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_datasets_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("source_id", "schema_name", "table_name", name="dataset_identity"),
    )
    op.create_table(
        "scan_runs",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "MANUAL",
                "SCHEDULED",
                name="scan_trigger",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="scan_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_scan_runs_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_runs")),
    )
    op.create_table(
        "alert_deliveries",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "SLACK", "EMAIL", name="alert_channel", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "FAILED",
                name="alert_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("provider_message_id", sa.String(length=250), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan_runs.id"],
            name=op.f("fk_alert_deliveries_scan_id_scan_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_deliveries")),
    )
    op.create_table(
        "expected_columns",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.Column("data_type_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nullable", sa.Boolean(), nullable=False),
        sa.Column("default", sa.String(length=1000), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_expected_columns_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expected_columns")),
        sa.UniqueConstraint("dataset_id", "name", name="expected_column_identity"),
    )
    op.create_table(
        "lineage_edges",
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("upstream_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("upstream_column", sa.String(length=63), nullable=False),
        sa.Column("downstream_dataset_id", sa.Uuid(), nullable=False),
        sa.Column("downstream_column", sa.String(length=63), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["downstream_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_lineage_edges_downstream_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_lineage_edges_pipeline_id_pipelines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["upstream_dataset_id"],
            ["datasets.id"],
            name=op.f("fk_lineage_edges_upstream_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lineage_edges")),
        sa.UniqueConstraint(
            "pipeline_id",
            "upstream_dataset_id",
            "upstream_column",
            "downstream_dataset_id",
            "downstream_column",
            name="lineage_edge_identity",
        ),
    )
    op.create_table(
        "observed_columns",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("schema_name", sa.String(length=63), nullable=False),
        sa.Column("table_name", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.Column("data_type_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nullable", sa.Boolean(), nullable=False),
        sa.Column("default", sa.String(length=1000), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan_runs.id"],
            name=op.f("fk_observed_columns_scan_id_scan_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observed_columns")),
    )
    op.create_table(
        "schema_changes",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("column_name", sa.String(length=63), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum(
                "ADD_COLUMN",
                "DROP_COLUMN",
                "TYPE_CHANGE",
                "NULLABILITY_CHANGE",
                name="change_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "INFO",
                "WARNING",
                "BREAKING",
                name="severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "OPEN",
                "ACCEPTED",
                "RESOLVED",
                name="change_state",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("before_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("baseline_version", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_schema_changes_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scan_runs.id"],
            name=op.f("fk_schema_changes_scan_id_scan_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_schema_changes_source_id_data_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schema_changes")),
    )
    op.create_index(
        "uq_schema_changes_open_fingerprint",
        "schema_changes",
        ["source_id", "fingerprint"],
        unique=True,
        postgresql_where=sa.text("state = 'OPEN'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_schema_changes_open_fingerprint",
        table_name="schema_changes",
        postgresql_where=sa.text("state = 'OPEN'"),
    )
    op.drop_table("schema_changes")
    op.drop_table("observed_columns")
    op.drop_table("lineage_edges")
    op.drop_table("expected_columns")
    op.drop_table("alert_deliveries")
    op.drop_table("scan_runs")
    op.drop_table("datasets")
    op.drop_table("pipelines")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
